[package]
name = "h-sharp-compiler"
version = "0.1.0"
edition = "2021"
authors = ["HackerOS Team <hackeros068@gmail.com>"]

[dependencies]
cranelift = "0.107.0"
cranelift-module = "0.107.0"
cranelift-frontend = "0.107.0"
cranelift-native = "0.107.0"
cranelift-object = "0.107.0"
target-lexicon = "0.12.14"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
anyhow = "1.0.81"
