[package]
name = "h-sharp-compiler"
version = "0.0.1"
edition = "2021"

[dependencies]
cranelift = "0.128.3"
cranelift-module = "0.128.3"
cranelift-frontend = "0.128.3"
cranelift-native = "0.128.3"
cranelift-object = "0.128.3"
target-lexicon = "0.12.14"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
h-sharp-parser = { path = "../parser" }
