[package]
name = "h-sharp"
version = "0.0.1"
edition = "2021"

[dependencies]
h-sharp-parser = { path = "../parser" }
h-sharp-compiler = { path = "../compiler" }
clap = { version = "4.5.4", features = ["derive"] }
indicatif = "0.17.8"
anyhow = "1.0.81"
tempfile = "3.10.1"
